10 A$="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX":REM
20 PRINT LEN(A$)
30 INPUT B$
40 PRINT B$;LEN(B$)
50 STOP
60 PRINT "CONT OK"
LIST 10
RUN
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
CONT
PRINT "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
A$="DIRECT":B$=A$+"!":PRINT B$
PRINT "ABC"
GOTO 60
